# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcc76bc2f2abffd3136377ea9f0a4b984d563587da4359d16152a4a965b686ed94e58cb44343bbac002cbb8a1a3025ca9645fe8a8bb2dc8ecfb44d87b3e784b9

test:
  secret_key_base: 7c1c4ce42115934ddb4cbbcca5b94999f890c44f426c680932508818c01e5bce3da8a01ea91498ab08dcfe7657cf82f2a65231dc35688853eade37e85f5e9cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
